name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull danielairinei/aws-demo:latest
      - name: Delete old docker container
        run: sudo docker rm -f aws-demo-container || true
      - name: Run latest docker container
        run: sudo docker run -d -p 80:8080 --name aws-demo-container danielairinei/aws-demo:latest
